name: CI

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 17.3.0

      - name: Install Dependencies
        run: npm ci

      - name: Lint
        run: npm run lint